version: "3.8"
services:
  es01:
    environment:
      - SEC_ENABLED=true
      - SEC_SSL=true
      - SEC_SSL_KEY=certs/es01.key
      - SEC_SSL_CERT=certs/es01.crt
      - SEC_SSL_CA=certs/ca.crt
  es02:
    environment:
      - SEC_ENABLED=true
      - SEC_SSL=true
      - SEC_SSL_KEY=certs/es02.key
      - SEC_SSL_CERT=certs/es02.crt
      - SEC_SSL_CA=certs/ca.crt
  es03:
    environment:
      - SEC_ENABLED=true
      - SEC_SSL=true
      - SEC_SSL_KEY=certs/es03.key
      - SEC_SSL_CERT=certs/es03.crt
      - SEC_SSL_CA=certs/ca.crt
  kibana:
    environment:
      - SERVER_NAME=kibana
      - SSL_ENABLED=true
      - ES_HOSTS=["https://es01:9200","https://es02:9200","https://es03:9200"]
      - URL=${URL}
      - KIBANA_USERNAME=kibana
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
  web:
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}   
  validator:
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}   
  etl:    
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}   
  