name: UpdateApp

on:
  workflow_dispatch:

jobs:
  compose_up:
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: docker compose
        run: docker-compose up --build -d
